version: '3.4'

services:
  mongo:
    restart: 'no'
    image: mongo:4.0.4-xenial
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db

  postgres:
    restart: 'no'
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD:postgres
    
  mongo-cli:
    restart: 'no'
    image: mongo:4.0.4-xenial
    depends_on:
      - mongo
    command: >
      sh -c 'mongo --host mongo '

  psql-cli:
    restart: 'no'
    image: postgres:11.1-alpine
    depends_on:
      - postgres
    links:
      - postgres:postgres
    command: >
      sh -c 'psql -h postgres -U postgres -p 5432'

  mongo-express:
    restart: 'no'
    image: mongo-express:0.49.0
    ports:
      - 8081:8081
    depends_on:
      - mongo
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    command: ["/wait-for-it.sh", "mongo:27017", "--", "/docker-entrypoint.sh"]

  adminer:
    image: adminer
    restart: 'no'
    ports:
      - 8080:8080